version: "2"
linters:
  enable:
    - bodyclose
    - gocheckcompilerdirectives
    - gocritic
    - misspell
    - nilerr
    - prealloc
    - unconvert
  disable:
    - errcheck
  settings:
    gocritic:
      # only the performance family
      disable-all: true
      enabled-tags:
        - performance
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
